In [2]:
import pandas as pd

In [3]:
npr = pd.read_csv("C:\\Users\\HP\\Downloads\\npr.csv")

In [4]:
npr.head(10)

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...
5  I did not want to join yoga class. I hated tho...
6  With a   who has publicly supported the debunk...
7  I was standing by the airport exit, debating w...
8  If movies were trying to be more realistic, pe...
9  Eighteen years ago, on New Year’s Eve, David F...

In [5]:
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [6]:
len(npr)

11992

# PREPROCESSING

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv= CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [9]:
dtm = cv.fit_transform(npr['Article'])

In [10]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [11]:
len(cv.get_feature_names_out())

54777

In [12]:
type(cv.get_feature_names_out())

numpy.ndarray

In [13]:
(cv.get_feature_names_out())[50000]

'transcribe'

In [14]:
(cv.get_feature_names_out())[41000]

'reproductive'

# LDA

In [15]:
from sklearn.decomposition import LatentDirichletAllocation

In [16]:
LDA = LatentDirichletAllocation(n_components=9, random_state=42)
LDA

LatentDirichletAllocation(n_components=9, random_state=42)

In [17]:
#This can take a while, we're dealing with a large amount of documents!
LDA.fit(dtm)

LatentDirichletAllocation(n_components=9, random_state=42)

# SHOWING STORED WORDS

In [18]:
len(cv.get_feature_names_out())

54777

In [19]:
import random

In [20]:
random_word_id=random.randint(0,54777)
cv.get_feature_names_out()[random_word_id]

'garcetti'

In [21]:
for i in range(10):
    random_word_id=random.randint(0,54777)
    print(cv.get_feature_names_out()[random_word_id])

deactivation
mcgregor
masterminding
grundmann
databook
schafer
spacing
vietnam
registers
cofounder


# SHOWING TOP WORDS PER TOPIC

In [22]:
len(LDA.components_)

9

In [23]:
type(LDA.components_)

numpy.ndarray

In [24]:
LDA.components_.shape

(9, 54777)

In [25]:
LDA.components_

array([[5.14350854e+00, 1.96675455e+03, 1.11117650e-01, ...,
        1.11227129e-01, 1.11111111e-01, 1.11111971e-01],
       [8.09580483e+00, 1.17359191e+02, 1.11111111e-01, ...,
        1.11111112e-01, 1.11111111e-01, 1.11114218e-01],
       [3.92418863e+00, 5.56788863e+02, 1.11111111e-01, ...,
        1.15689749e-01, 2.11089722e+00, 1.11126129e-01],
       ...,
       [1.26699266e+01, 3.55606484e+02, 1.11111111e-01, ...,
        1.11111112e-01, 1.11217805e-01, 1.11112413e-01],
       [2.68444364e+01, 5.49094603e+02, 1.11111111e-01, ...,
        1.11145091e-01, 1.11111111e-01, 1.11111111e-01],
       [1.11188139e-01, 3.12877152e+02, 1.11111111e-01, ...,
        4.93753496e+00, 1.11120527e-01, 1.11112769e-01]])

In [26]:
len(LDA.components_[0])

54777

In [27]:
single_topic=LDA.components_[0]

In [53]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [29]:
import numpy as np


arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [30]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [31]:
single_topic.argsort()[-10:]

array([    1, 18349, 33390, 32089, 10421, 31464, 10425, 22673, 42561,
       42993], dtype=int64)

In [32]:
top_word_indices = single_topic.argsort()[-10:]

In [33]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

000
federal
new
money
companies
million
company
health
said
says


In [34]:
top_twenty_indices = single_topic.argsort()[-20:]

In [35]:
for index in top_twenty_indices:
    print(cv.get_feature_names_out()[index])

industry
tax
business
pay
percent
care
people
government
insurance
year
000
federal
new
money
companies
million
company
health
said
says


# grab highest probability words per topic

In [55]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['care', 'people', 'government', 'insurance', 'year', '000', 'federal', 'new', 'money', 'companies', 'million', 'company', 'health', 'said', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['npr', 'new', 'military', 'told', 'russian', 'campaign', 'security', 'obama', 'white', 'news', 'russia', 'house', 'president', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['make', 'family', 'way', 'home', 'water', 'day', 'world', 'time', 'years', 'new', 'food', 'people', 'just', 'like', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['new', 'don', 'percent', 'medical', 'children', 'disease', 'just', 'care', 'patients', 'like', 'study', 'women', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['supreme', 'order', 'states', 'city', 'federal', 'president', 'country', 'rights', 'government', 'law', 'state', 'people', 'said', 'court', 'says']


THE TOP 15 WORDS FOR TOPIC #5
['going', 'story', 've', 'don', 'life', 'new', 'way', 'really', 'time', 'music', 'know', 'think', 'p

In [37]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [38]:
dtm.shape

(11992, 54777)

In [39]:
len(npr)

11992

In [40]:
topic_results = LDA.transform(dtm)

In [41]:
topic_results

array([[7.60790674e-03, 8.85726993e-01, 1.74802439e-04, ...,
        1.74809413e-04, 1.74783046e-04, 1.05616309e-01],
       [1.52357260e-02, 9.57264532e-01, 3.42052301e-04, ...,
        3.42040792e-04, 2.54473633e-02, 3.42187254e-04],
       [2.54940612e-04, 8.95032226e-01, 2.54940340e-04, ...,
        2.54926756e-04, 2.55038075e-04, 1.03183104e-01],
       ...,
       [3.08845831e-04, 7.53570424e-02, 1.47098578e-01, ...,
        3.08837240e-04, 1.28581070e-01, 3.08896534e-04],
       [3.35851249e-04, 9.80625222e-02, 3.35841820e-04, ...,
        3.35902594e-04, 3.35854363e-04, 8.31067213e-01],
       [1.49476246e-01, 1.97117234e-04, 2.86049226e-01, ...,
        1.97129288e-04, 1.97144614e-04, 2.11131231e-01]])

In [42]:
topic_results.shape

(11992, 9)

In [46]:
topic_results[0]

array([7.60790674e-03, 8.85726993e-01, 1.74802439e-04, 1.74798716e-04,
       1.74800239e-04, 1.74797912e-04, 1.74809413e-04, 1.74783046e-04,
       1.05616309e-01])

In [47]:
topic_results[0].round(2)

array([0.01, 0.89, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.11])

In [49]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [50]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 8, 4], dtype=int64)

In [51]:
npr['topic']=topic_results.argmax(axis=1)

In [52]:
npr

Article  topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      6
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      7
11988    Trump is busy these days with victory tours,...      1
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      8
11991  Voters in the English city of Sunderland did s...      4

[11992 rows x 2 columns]

In [56]:
#NON NEGATIVE MATRIX