In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("C:\\Users\\HP\\Downloads\\npr.csv")
df

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [4]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [6]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [7]:
len(df)

11992

In [8]:
#Preprocessing
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
cv= CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [11]:
dtm = cv.fit_transform(df['Article'])

In [12]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [13]:
len(cv.get_feature_names_out())

54777

In [14]:
type(cv.get_feature_names_out())

numpy.ndarray

In [16]:
(cv.get_feature_names_out())[25000]

'infiltrated'

In [17]:
(cv.get_feature_names_out())[44000]

'shaggy'

In [18]:
#LDA
from sklearn.decomposition import LatentDirichletAllocation

In [19]:
LDA = LatentDirichletAllocation(n_components=10, random_state=42)
LDA

LatentDirichletAllocation(random_state=42)

In [20]:
#This can take a while, we're dealing with a large amount of documents!
LDA.fit(dtm)

LatentDirichletAllocation(random_state=42)

In [21]:
#showing stored words
len(cv.get_feature_names_out())

54777

In [22]:
import random

In [26]:
random_word_id=random.randint(0,54777)
cv.get_feature_names_out()[random_word_id]

'martí'

In [24]:
for i in range(10):
    random_word_id=random.randint(0,54777)
    print(cv.get_feature_names_out()[random_word_id])

schopp
peace
sulzberger
rutabagas
son
bekir
shortfalls
stint
grit
buyback


In [25]:
#SHOWING STOP WORDS PER TOPIC
len(LDA.components_)

10

In [27]:
type(LDA.components_)

numpy.ndarray

In [28]:
LDA.components_.shape

(10, 54777)

In [29]:
LDA.components_

array([[5.11072577e+00, 1.94461867e+03, 1.00001806e-01, ...,
        1.00005562e-01, 1.00000000e-01, 1.00001005e-01],
       [7.90134677e+00, 9.65122359e+01, 1.00000000e-01, ...,
        1.00000000e-01, 1.00000000e-01, 1.00005679e-01],
       [5.31852874e+00, 3.00433521e+02, 1.00000000e-01, ...,
        6.09994114e+00, 2.09990395e+00, 2.09985534e+00],
       ...,
       [2.70759028e+01, 5.39924878e+02, 1.00000000e-01, ...,
        1.00009334e-01, 1.00000000e-01, 1.00000000e-01],
       [1.00044538e-01, 3.22049903e+02, 1.00000000e-01, ...,
        1.00002615e-01, 1.00002538e-01, 1.00002208e-01],
       [2.79006612e-01, 5.87022720e+02, 1.00000000e-01, ...,
        1.00005607e-01, 1.00006588e-01, 1.00000000e-01]])

In [30]:
len(LDA.components_[0])

54777

In [31]:
single_topic=LDA.components_[0]

In [32]:
single_topic.argsort()

array([18302,  2475, 44967, ..., 10425, 42561, 42993], dtype=int64)

In [33]:
#CODE FOR UNDERSTANDING PURPOSE FOR ARR NOT RELATED TO DATA
import numpy as np


arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [34]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [35]:
single_topic.argsort()[-10:]

array([    1, 18349, 33390, 32089, 10421, 31464, 22673, 10425, 42561,
       42993], dtype=int64)

In [36]:
top_word_indices = single_topic.argsort()[-10:]

In [38]:
for index in top_word_indices:
    print(cv.get_feature_names_out()[index])

000
federal
new
money
companies
million
health
company
said
says


In [39]:
top_twenty_indices = single_topic.argsort()[-20:]

In [40]:
for index in top_twenty_indices:
    print(cv.get_feature_names_out()[index])

industry
tax
business
percent
pay
people
care
government
year
insurance
000
federal
new
money
companies
million
health
company
said
says


In [45]:
#GRAB HIGHEST PROBABILITY WORDS PER TOPIC
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 10 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print('\n')

THE TOP 10 WORDS FOR TOPIC #0
['000', 'federal', 'new', 'money', 'companies', 'million', 'health', 'company', 'said', 'says']


THE TOP 10 WORDS FOR TOPIC #1
['russian', 'campaign', 'obama', 'news', 'white', 'russia', 'house', 'president', 'said', 'trump']


THE TOP 10 WORDS FOR TOPIC #2
['day', 'water', 'time', 'years', 'people', 'food', 'new', 'just', 'like', 'says']


THE TOP 10 WORDS FOR TOPIC #3
['time', 'family', 'children', 'years', 'just', 'women', 'world', 'like', 'people', 'says']


THE TOP 10 WORDS FOR TOPIC #4
['country', 'president', 'rights', 'government', 'people', 'law', 'state', 'said', 'court', 'says']


THE TOP 10 WORDS FOR TOPIC #5
['new', 'way', 'time', 'really', 'know', 'think', 'music', 'people', 'just', 'like']


THE TOP 10 WORDS FOR TOPIC #6
['people', 'time', 'schools', 'education', 'just', 'new', 'like', 'students', 'school', 'says']


THE TOP 10 WORDS FOR TOPIC #7
['attack', 'reported', 'killed', 'according', 'told', 'says', 'reports', 'people', 'police', 's

In [42]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [43]:
dtm.shape

(11992, 54777)

In [44]:
len(df)

11992

In [46]:
topic_results = LDA.transform(dtm)

In [47]:
topic_results

array([[8.78101114e-03, 9.11263140e-01, 1.57269537e-04, ...,
        1.57262374e-04, 7.88549762e-02, 1.57267682e-04],
       [1.49936770e-02, 9.47175958e-01, 3.07748182e-04, ...,
        3.56760693e-02, 3.07795385e-04, 3.07734183e-04],
       [2.29395268e-04, 9.20339979e-01, 2.29393168e-04, ...,
        2.29431126e-04, 7.78248413e-02, 2.29384000e-04],
       ...,
       [2.77856521e-04, 2.31282169e-02, 2.11661501e-02, ...,
        1.24124773e-01, 2.05148990e-02, 3.72486849e-01],
       [3.02173904e-04, 1.14646204e-01, 3.02169515e-04, ...,
        3.02189479e-04, 7.80849469e-01, 3.02163423e-04],
       [1.53516092e-01, 1.77345311e-04, 2.47495487e-01, ...,
        1.77354607e-04, 1.80685598e-01, 1.77349551e-04]])

In [48]:
topic_results.shape

(11992, 10)

In [49]:
topic_results[0]

array([8.78101114e-03, 9.11263140e-01, 1.57269537e-04, 1.57265808e-04,
       1.57268730e-04, 1.57266519e-04, 1.57271636e-04, 1.57262374e-04,
       7.88549762e-02, 1.57267682e-04])

In [50]:
topic_results[0].round(2)

array([0.01, 0.91, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.08, 0.  ])

In [51]:
df.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [52]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 8, 4], dtype=int64)

In [53]:
df['topic']=topic_results.argmax(axis=1)

In [54]:
df

Article  topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      6
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      7
11988    Trump is busy these days with victory tours,...      1
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      8
11991  Voters in the English city of Sunderland did s...      4

[11992 rows x 2 columns]