In [1]:
from sklearn.feature_extraction.text import CountVectorizer


documents = ["Machine learning is amazing!",
            "Deep learning is a subset of machine learning.",
            "Natural language processing is a part of AI.",
            "AI is transforming the world."]

cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = cv.fit_transform(documents) # convert text to document-term matrix

print(cv.get_feature_names_out()) #display remaining words
print(dtm.toarray())  # show the word counts in documents

['ai' 'learning' 'machine']
[[0 1 1]
 [0 2 1]
 [1 0 0]
 [1 0 0]]


In [2]:
import random
from sklearn.feature_extraction.text import CountVectorizer

#sample text corpus
documents = ["Machine learning is amazing!",
            "Deep learning is a subset of machine learning.",
            "Natural language processing is a part of AI."]

#convert text into a document-term matrix=DTM
cv = CountVectorizer(stop_words='english')
dtm = cv.fit_transform(documents)
#get feature names
feature_names = cv.get_feature_names_out() #updated method

#generate 10 random words from the vocabulary
for i in range(10):
    random_word_id = random.randint(0, len(feature_names) -1) #use the actual vocabulary size
    print(feature_names[random_word_id])

natural
machine
subset
ai
learning
language
language
learning
ai
language


In [3]:
import numpy as np
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

#sample corpus
documents = ["I love Machine learning and data science!",
            "Deep learning is a subset of machine learning.",
            "I enjoy playing football and watching sports.",
             "Sports analytics is an interesting field"]

#convert text to document-term matrix
vectorizer= CountVectorizer(stop_words='english')
dtm = vectorizer.fit_transform(documents)

#Train the LDA model
lda = LatentDirichletAllocation(n_components=2, random_state=42)
lda.fit(dtm)

#get topic distribution for each document
topic_results= lda.transform(dtm) #shape: (num_docs, num_topics)

#identify the dominant topic for each document
dominant_topics = topic_results.argmax(axis=1)

#print results
for i, topic in enumerate(dominant_topics):
    print(f"Document {i+1} is mostly about Topic {topic}")

Document 1 is mostly about Topic 1
Document 2 is mostly about Topic 0
Document 3 is mostly about Topic 1
Document 4 is mostly about Topic 0
